### ISSUE TITLE
Crash on dedicated server: java.lang.NullPointerException: Registry Object not present: moguns:m1_garand

### ISSUE THREAD

**Issue by Jetpack-Cat** [Bomb787/MoGuns-Addon#11]
Hey i'm doing an update to my modpack and adding moguns (https://www.curseforge.com/minecraft/modpacks/jetpack-cat)
When players make or join a dedicated server and fire ANY gun, even one of the default crayfish mod guns, the client crashes. Here's the crash log, I included mo guns in my last update, which is now crashing for everyone, and was going to add all of the guns into the loot pool in the next update. Now I have to put that last version into alpha state and wait on releasing the next update until this can get fixed, otherwise I have to remove the mod.

MC 1.16.5 latest forge version

[crash-2023-01-16_00.22.15-client.txt](https://github.com/Bomb787/MoGuns-Addon/files/10423820/crash-2023-01-16_00.22.15-client.txt)

**Comment by Bomb787** [comment]
It seems to work fine for me with only Mo' Guns, CGM and Obfuscate installed. Are you doing anything that could be modifying the registry?

**Comment by Bomb787** [comment]
Issue appears to have resolved itself.
