### ISSUE TITLE
Guns glitched

### ISSUE THREAD

**Issue by InfinitySnake21** [Bomb787/MoGuns-Addon#2]
The guns have no sound and they require no reloading please help.

**Comment by Bomb787** [comment]
Can you give us more information on what you were doing?

**Comment by Spartaboi** [comment]
Having the same problem here. Have the mod installed on a server, and there is no audio firing, or reloading. Guns will reload with ammo, but the ammo amount will not go down, giving guns infinite ammo. This problem also extends to guns from other addons, and even the base mod, but they don't exist when the mod isn't installed.

**Comment by Bomb787** [comment]
Are you guys using the latest version? There is a singleplayer and multiplayer version, make sure you're running the right one.

**Comment by Spartaboi** [comment]
> 

Was running the 1.5 server version. Had problems when it was on the server, but in singleplayer, it didn't have any problems.

**Comment by Bomb787** [comment]
Can you provide some logs?

**Comment by Spartaboi** [comment]
https://paste.shockbyte.com/egiwakiqovofuwozisub

Console popped up more specific stuff for the mod like:

26.02 05:49:16 [Server] main/WARN [ne.mi.re.ForgeRegistry/REGISTRIES]: Registry Item: Object did not get ID it asked for. Name: moguns:scarl Expected: 2268 Got: 2308

26.02 05:49:16 [Server] main/WARN [ne.mi.re.ForgeRegistry/REGISTRIES]: Registry SoundEvent: Object did not get ID it asked for. Name: moguns:item.thompson_fire Expected: 1057 Got: 1060

**Comment by Jacobwasbeast** [comment]
I have the fix in my repo.
I decompiled the original server jar to get the updated code and removed some client code to get the ammo working.

**Comment by Jacobwasbeast** [comment]
for reference the problematic code was
in the Recoil Shooting Event
`
@SubscribeEvent
public static void recoil(GunFireEvent.Post event) {
  `

I fixed it with 

`
@SubscribeEvent
public static void recoil(Post event) {
if(event.isClient()) {
`

**Comment by Bomb787** [comment]
> for reference the problematic code was in the Recoil Shooting Event `@SubscribeEvent public static void recoil(GunFireEvent.Post event) {`
> 
> I fixed it with
> 
> `@SubscribeEvent public static void recoil(Post event) { if(event.isClient()) {`

Hmm, weird, I already have that code in my code from 1.4. I've been quite busy but a fix should be coming relatively soon.
