### ISSUE TITLE
Crash with MoGuns when joining singleplayer world.

### ISSUE THREAD

**Issue by michlbro** [Bomb787/MoGuns-Addon#6]
Game crashes when player tries to load singleplayer world, but can join a multiplayer world like normal except the server will also say the same error while still being playable.

Server-Log(On world loading): https://pastebin.com/3YXcmnkw
Client-Log(when loading singleplayer world): https://pastebin.com/7dsMKFS5

**Comment by Bomb787** [comment]
Fixed

**Comment by michlbro** [comment]
Sorry to bother you again, but I tried building the current version with gradlew and I'm getting some errors.

**Comment by Bomb787** [comment]
I can't help you if you don't tell what kind of errors you're getting

**Comment by michlbro** [comment]
[gadlewlog.txt](https://github.com/Bomb787/MoGuns-Addon/files/9404879/gadlewlog.txt)

**Comment by Bomb787** [comment]
Redownload the repo, there's some files that shouldn't be there

**Comment by michlbro** [comment]
Sorry if I'm bothering you (I might be doing this completely wrong "gradlew build"), I've tried redownloading the repo and trying both 1.18.2 and main branches. But it still gives me errors when building both but with different errors. 
main:
[gradlewtxt.txt](https://github.com/Bomb787/MoGuns-Addon/files/9410483/gradlewtxt.txt)
1.18.2:
[gradlewtxt.txt](https://github.com/Bomb787/MoGuns-Addon/files/9410484/gradlewtxt.txt)

**Comment by Bomb787** [comment]
redownload it again, I just deleted some stuff that should've been deleted way before
